//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using PagedList;
    using System;
    using System.Collections.Generic;

    public partial class ITEMS
    {
        public int StockId { get; set; }
        public string StockCode { get; set; }
        public string Name_Item { get; set; }
        public Nullable<int> Type_Id { get; set; }
        public string Type { get; set; }
        public double COST_PRICE { get; set; }
        public int STOCK_LEVEL { get; set; }
        public Nullable<int> MIN_MIN_STOCK_LEVEL { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string Vendor_Name { get; set; }
        public double Retail_Margin { get; set; }
        public double Trade_Margin { get; set; }
        public Nullable<double> Add_Quantity { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<int> Free_Items { get; set; }
        public IPagedList<ITEMS> SearchResults { get; set; }
        public string SearchButton { get; set; }
        public int? Page { get; set; }
    }
}
