//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WICKRAMA_STORESEntities : DbContext
    {
        public WICKRAMA_STORESEntities()
            : base("name=WICKRAMA_STORESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ITEMS> ITEMS { get; set; }
        public virtual DbSet<PaymentTerms> PaymentTerms { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<tb_Cart> tb_Cart { get; set; }
        public virtual DbSet<tb_Customer> tb_Customer { get; set; }
        public virtual DbSet<tb_Employee> tb_Employee { get; set; }
        public virtual DbSet<tb_PurchaseReturns> tb_PurchaseReturns { get; set; }
        public virtual DbSet<tb_Sales> tb_Sales { get; set; }
        public virtual DbSet<tb_SalesOrder> tb_SalesOrder { get; set; }
        public virtual DbSet<tb_SalesReturns> tb_SalesReturns { get; set; }
        public virtual DbSet<tb_Supplier> tb_Supplier { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
