//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_ELEMENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER_ELEMENTS()
        {
            this.ProductsAllocatedToOrders = new HashSet<ProductsAllocatedToOrders>();
        }
    
        public int ITEM_ID { get; set; }
        public Nullable<int> STOCK_CODE { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public Nullable<int> ORDER_NO { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> BUY_PRICE { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual ITEMS ITEMS { get; set; }
        public virtual OrderElementsStatusLookup OrderElementsStatusLookup { get; set; }
        public virtual ORDERS ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsAllocatedToOrders> ProductsAllocatedToOrders { get; set; }
    }
}
