//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using PagedList;
    using System;
    using System.Collections.Generic;

    public partial class sales_order
    {
        public int Sales_order_id { get; set; }
        public string CUSTOMER_NO { get; set; }
        public System.DateTime DATE_PLACED { get; set; }
        public int INVOICE_NO { get; set; }
        public string Employee_id { get; set; }
        public Nullable<System.DateTime> Delivery_date { get; set; }
        public IPagedList<sales_order> SearchResults { get; set; }
        public string SearchButton { get; set; }
        public int? Page { get; set; }
    }
}
