//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using PagedList;
    using System;
    using System.Collections.Generic;

    public partial class tb_Cart
    {
        public int ITEM_ID { get; set; }
        public Nullable<int> STOCK_CODE { get; set; }
        public Nullable<float> QUANTITY { get; set; }
        public Nullable<int> ORDER_NO { get; set; }
        public double UNIT_PRICE { get; set; }
        public double BUY_PRICE { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<double> Total { get; set; }
        public string Name_Product { get; set; }
        public Nullable<int> Bill_No { get; set; }
        public string Route { get; set; }
        public string sales_id { get; set; }
        public string Discount { get; set; }
        public string Code_Product { get; set; }
        public IPagedList<tb_Cart> SearchResults { get; set; }
        public string SearchButton { get; set; }
        public int? Page { get; set; }
    }
}
